all: mandelbox

clean:
	rm -f *.o mandelbulb mandelbox boxserial bulbserial *~

bulbserial:
	make -f make.serial_bulb

boxserial:
	make -f make.serial_box

mandelbulb:
	make -f make.bulb

mandelbox:
	make -f make.box	
